config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :players
  get "search", to: "players#search"
  root "players#index"
  get "graphs", to: "players#graphs"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]
  # GET /players or /players.json
  def index
    
    @players = Player.order(params[:sort]).page(params[:page]).per(50)
  end

  def search
      @players = Player.where("lower(name) LIKE :q OR lower(position) LIKE :q OR lower(draft_team) LIKE :q OR lower(nationality) LIKE :q",
       q: "%#{params[:q].downcase}%").order(:name).page(params[:page]).per(50)
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :position, :games_played, :goals, :assists, :points, :plus_minus, :draft_team, :nationality, :draft_year, :draft_pick, :retirement_year, :penalty_minutes, :point_share, :amateur_team)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark justify-content-center">
    
  <div class="container-fluid">
    <%= link_to 'NHL Draft Stats', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Players', players_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Graphs', graphs_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>

        <li class="nav-item">
            <%= link_to 'Add Player', new_player_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>

        <% else %>

        <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class:"nav-link" %>
        </li>

        <% end %>
        
      </ul>

      <form class="d-flex" action="/search">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>NHL Player Stats</h1>
<p>test</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-dark" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>NHL Draft Stats</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <div class="container">
    <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Full name" %>
  </div>

  <div class="field mb-3">
    <% form.label :position %>
    <%= form.text_field :position, class:"form-control", placeholder:"Position" %>
  </div>

  <div class="field mb-3">
    <% form.label :games_played %>
    <%= form.number_field :games_played, class:"form-control", placeholder:"Number of played games" %>
  </div>

  <div class="field mb-3">
    <% form.label :goals %>
    <%= form.number_field :goals, class:"form-control", placeholder:"Number of goals" %>
  </div>

  <div class="field mb-3">
    <% form.label :assists %>
    <%= form.number_field :assists, class:"form-control", placeholder:"Number of assists" %>
  </div>

  <div class="field mb-3">
    <% form.label :points %>
    <%= form.number_field :points, class:"form-control", placeholder:"Number of points" %>
  </div>

  <div class="field mb-3">
    <% form.label :plus_minus %>
    <%= form.number_field :plus_minus, class:"form-control", placeholder:"Plus-minus" %>
  </div>

  <div class="field mb-3">
    <% form.label :draft_team %>
    <%= form.text_field :draft_team , class:"form-control", placeholder:"Team that drafted the player" %>
  </div>

  <div class="field mb-3">
    <% form.label :nationality %>
    <%= form.text_field :nationality , class:"form-control", placeholder:"Nationality"%>
  </div>

  <div class="field mb-3">
    <% form.label :draft_year %>
    <%= form.number_field :draft_year , class:"form-control", placeholder:"Draft year"%>
  </div>

  <div class="field mb-3">
    <% form.label :draft_pick %>
    <%= form.number_field :draft_pick, class:"form-control", placeholder:"Draft pick number" %>
  </div>

  <div class="field mb-3">
    <% form.label :retirement_year %>
    <%= form.number_field :retirement_year, class:"form-control", placeholder:"Retirement year" %>
  </div>

  <div class="field mb-3">
    <% form.label :penalty_minutes %>
    <%= form.number_field :penalty_minutes, class:"form-control", placeholder:"Penalty minutes" %>
  </div>

  <div class="field mb-3">
    <% form.label :point_share %>
    <%= form.number_field :point_share, class:"form-control", placeholder:"Point share rating" %>
  </div>

  <div class="field mb-3">
    <% form.label :amateur_team %>
    <%= form.text_field :amateur_team, class:"form-control", placeholder:"Amateur team" %>
  </div>

  <div class="actions ">
    <%= form.submit class:"btn btn-outline-success" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Edit <%= @player.name %></h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player, class:"btn btn-outline-primary" %> 
<%= link_to 'Back', players_path, class:"btn btn-outline-danger" %>

app/views/players/graphs.html.erb
<h1 class="d-flex justify-content-center">Graphs</h1>
<br/>
<h4 class="d-flex justify-content-center">Number of players drafted by each team</h4>
<br/>
<%= bar_chart Player.group(:draft_team).order(:draft_team).count,  height: "850px", colors: ["#005075", "#ffa600"],
 label: "Players",xtitle: "Number of players", ytitle: "Team" %>
<br/><br/><br/>
<h4 class="d-flex justify-content-center">Number of players drafted by year</h4>
<br/>
<%= column_chart Player.group(:draft_year).count, colors: ["#005075", "#ffa600"], height: "400px", label: "Players" %>
<br/><br/><br/>
<h4 class="d-flex justify-content-center">Player breakdown by position</h4>
<br/>
<%= pie_chart Player.group(:position).count, height: "500px" %>

app/views/players/index.html.erb
<div class="alert alert-primary text-center" role="alert">
  Data is taken at the moment of 2022 NHL Entry Draft: 08/07/22
</div>

<h1 class="text-center">NHL Player Statistics</h1>

<h4 class="text-center">
Total number of players: 
<%= Player.count %>
</h4>

<div class="d-flex justify-content-center">
  <%= paginate @players %>
</div>

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="thead-dark">
    <tr>
      <th><%= link_to "Name", :sort => "name"%></th>
      <th><%= link_to"Position", :sort => "position"%></th>
      <th>Games</th>
      <th>Goals</th>
      <th>Assists</th>
      <th>Points</th>
      <th>+/-</th>
      <th><%= link_to"Draft team", :sort => "draft_team"%></th>
      <th><%= link_to"Nationality", :sort => "nationality"%></th>
      <th>Draft year</th>
      <th>Draft pick</th>
      <th>Penalty minutes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.games_played %></td>
        <td><%= player.goals %></td>
        <td><%= player.assists %></td>
        <td><%= player.points %></td>
        <td><%= player.plus_minus %></td>
        <td><%= player.draft_team %></td>
        <td><%= player.nationality %></td>
        <td><%= player.draft_year %></td>
        <td><%= player.draft_pick %></td>        
        <td><%= player.penalty_minutes %></td>        
        <td><%= link_to 'Details', player, class:"btn btn-outline-primary btn-sm"%></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_player_path(player), class:"btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= paginate @players %>
</div>

<% if user_signed_in? %>
  <%= link_to 'New Player', new_player_path, class:"btn btn-dark text-white" %>
<% end %>

app/views/players/new.html.erb
<h1>Add New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path, class:"btn btn-outline-danger" %>

app/views/players/search.html.erb
<div class="alert alert-primary text-center" role="alert">
  Data is taken at the moment of 2022 NHL Entry Draft: 08/07/22
</div>

<h1 class="text-center">Search Results</h1>

<h4 class="text-center">
Total search results: 
<%= @players.total_count %>
</h4>

<div class="d-flex justify-content-center">
  <%= paginate @players %>
</div>

<table class="table table-striped table-hover table-bordered table-sm">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Games</th>
      <th>Goals</th>
      <th>Assists</th>
      <th>Points</th>
      <th>+/-</th>
      <th>Draft team</th>
      <th>Nationality</th>
      <th>Draft year</th>
      <th>Draft pick</th>
      
      <th>Penalty minutes</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.games_played %></td>
        <td><%= player.goals %></td>
        <td><%= player.assists %></td>
        <td><%= player.points %></td>
        <td><%= player.plus_minus %></td>
        <td><%= player.draft_team %></td>
        <td><%= player.nationality %></td>
        <td><%= player.draft_year %></td>
        <td><%= player.draft_pick %></td>
        
        <td><%= player.penalty_minutes %></td>
        
        <td><%= link_to 'Details', player, class:"btn btn-outline-primary btn-sm"%></td>
        
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_player_path(player), class:"btn btn-outline-secondary btn-sm" %></td>
          <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= paginate @players %>
</div>

<% if user_signed_in? %>
  <%= link_to 'New Player', new_player_path, class:"btn btn-dark text-white" %>
<% end %>

app/views/players/show.html.erb
<div class="col-md-6 ">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2><%= @player.name %></h2>
          <p>
            <strong>Position:</strong>
            <%= @player.position %>
          </p>

          <p>
  <strong>Games played:</strong>
  <%= @player.games_played %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @player.goals %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @player.assists %>
</p>

<p>
  <strong>Points:</strong>
  <%= @player.points %>
</p>

<p>
  <strong>Plus minus:</strong>
  <%= @player.plus_minus %>
</p>

<p>
  <strong>Draft team:</strong>
  <%= @player.draft_team %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @player.nationality %>
</p>

<p>
  <strong>Draft year:</strong>
  <%= @player.draft_year %>
</p>

<p>
  <strong>Draft pick:</strong>
  <%= @player.draft_pick %>
</p>

<p>
  <strong>Retirement year:</strong>
  <%= @player.retirement_year %>
</p>

<p>
  <strong>Penalty minutes:</strong>
  <%= @player.penalty_minutes %>
</p>

<p>
  <strong>Point share:</strong>
  <%= @player.point_share %>
</p>

<p>
  <strong>Amateur team:</strong>
  <%= @player.amateur_team %>
</p>
          <% if user_signed_in?%>
            <%= link_to 'Edit', edit_player_path(@player), class:"btn btn-outline-warning" %>
          <% end %>
          
          <%= link_to 'Back', players_path, class:"btn btn-outline-danger" %>
        </div>
      </div>